Repository explosion/spacy-llm, pull requests merged in 2023-09, with the labels that each got.

#278 Updates for CoT implementation
  spacy_llm/tasks/__init__.py
  spacy_llm/tasks/spancat/registry.py
Labels: enhancement

#279 Simplify test suite
  spacy_llm/tests/tasks/examples/ner.json
  spacy_llm/tests/tasks/examples/ner.jsonl
  spacy_llm/tests/tasks/examples/ner.yml
  spacy_llm/tests/tasks/legacy/test_ner.py
  spacy_llm/tests/tasks/legacy/test_spancat.py
  spacy_llm/tests/tasks/test_lemma.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_sentiment.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_summarization.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: tests, Test external

#277 add_label functionality
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/builtin_task.py
  spacy_llm/tests/tasks/legacy/test_ner.py
  spacy_llm/tests/tasks/legacy/test_spancat.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
  spacy_llm/ty.py
Labels: enhancement, feat/task, Test external

#282 Skip Llama2 tests
  spacy_llm/tests/models/test_llama2.py
Labels: chore, CI, Test GPU

#236 increase default max_tokens for older non-chat OpenAI models so NER/spancat works
  README.md
  spacy_llm/models/hf/dolly.py
  spacy_llm/models/hf/falcon.py
  spacy_llm/models/hf/llama2.py
  spacy_llm/models/hf/openllama.py
  spacy_llm/models/hf/stablelm.py
  spacy_llm/models/langchain/model.py
  spacy_llm/models/rest/anthropic/registry.py
  spacy_llm/models/rest/cohere/registry.py
  spacy_llm/models/rest/openai/__init__.py
  spacy_llm/models/rest/openai/registry.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/models/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_lemma.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_sentiment.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_summarization.py
  spacy_llm/tests/tasks/test_textcat.py
  spacy_llm/tests/test_combinations.py
  spacy_llm/util.py
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/rel_openai/fewshot.cfg
  usage_examples/rel_openai/zeroshot.cfg
  usage_examples/tests/test_readme_examples.py
  usage_examples/textcat_openai/fewshot.cfg
  usage_examples/textcat_openai/zeroshot.cfg
Labels: feat/model, Test external, Test GPU

#283 Consistently use same default model
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/openai/model.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/__init__.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/test_combinations.py
Labels: feat/model

#284 Update readme for 0.5.0
  README.md
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/streamlit/streamlit_app.py
  usage_examples/textcat_openai/fewshot.cfg
  usage_examples/textcat_openai/zeroshot.cfg
Labels: documentation

#287 Release 0.5.0
  migration_guide.md
  setup.cfg
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/sentiment/parser.py
  spacy_llm/ty.py
  usage_examples/streamlit/streamlit_app.py
  usage_examples/tests/test_usage_examples.py
  usage_examples/textcat_dolly/fewshot.cfg
  usage_examples/textcat_dolly/zeroshot.cfg
Labels: documentation

#288 Simplify usage example in readme
  README.md
Labels: documentation

#291 Bump version to 0.5.1
  setup.cfg
Labels: chore

#292 Synch `develop` with `main`
  README.md
  migration_guide.md
  requirements.txt
  setup.cfg
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/sentiment/parser.py
  spacy_llm/ty.py
  usage_examples/streamlit/streamlit_app.py
  usage_examples/tests/test_usage_examples.py
  usage_examples/textcat_dolly/fewshot.cfg
  usage_examples/textcat_dolly/zeroshot.cfg
Labels: chore
