Repository explosion/spacy-llm, pull requests merged in 2023-06, with the labels that each got.

#155 chore: add isort to pre-commit
  .github/workflows/validate.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: chore

#156 Sync `develop` with `main`
  .github/workflows/validate.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: chore

#158 Use equality operator in tests
  spacy_llm/ty.py
Labels: bug

#154 clean up assemble to call assemble_from_config
  spacy_llm/util.py
Labels: refactoring

#160 Update example 4 with 2 imports
  README.md
Labels: documentation

#162 Pass `model` instead of `model_name` to langchain
  requirements-dev.txt
  setup.cfg
  spacy_llm/backends/integration/langchain.py
Labels: bug, feat/backend

#102 Add streamlit demo
  usage_examples/streamlit/streamlit_app.py
Labels: documentation

#127 feat: add optional prompt storage support
  README.md
  requirements-dev.txt
  setup.cfg
  spacy_llm/backends/integration/langchain.py
  spacy_llm/backends/rest/noop.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/noop.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/ty.py
  spacy_llm/util.py
  usage_examples/streamlit/streamlit_app.py
Labels: feature

#169 Sync `develop` with `main`
  spacy_llm/pipeline/llm.py
  usage_examples/streamlit/streamlit_app.py
Labels: chore

#164 Add lemmatization task `spacy.Lemma.v1`
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/__init__.py
  spacy_llm/tasks/lemma.py
  spacy_llm/tasks/templates/lemma.jinja
  spacy_llm/tasks/util/examples.py
  spacy_llm/tasks/util/span.py
  spacy_llm/tests/tasks/examples/lemma_examples.json
  spacy_llm/tests/tasks/examples/lemma_examples.jsonl
  spacy_llm/tests/tasks/examples/lemma_examples.yml
  spacy_llm/tests/tasks/templates/lemma_template.jinja2
  spacy_llm/tests/tasks/test_lemma.py
  spacy_llm/ty.py
Labels: feature, feat/task

#157 Add Anthropic REST backend
  .github/workflows/external.yml
  spacy_llm/backends/rest/__init__.py
  spacy_llm/backends/rest/anthropic.py
  spacy_llm/backends/rest/registry.py
  spacy_llm/tests/backends/test_anthropic.py
  spacy_llm/tests/compat.py
Labels: enhancement, feat/backend

#80 Add optional logging of generated prompt/response
  README.md
  spacy_llm/__init__.py
  spacy_llm/cache.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/test_cache.py
Labels: feature

#173 Bump version
  setup.cfg
Labels: chore

#177 Update `develop` from `main`
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/textcat.py
  spacy_llm/tasks/util/span.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
  spacy_llm/ty.py
Labels: chore

#178 Optional type validation
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/ty.py
Labels: enhancement

#182 Sync develop with latest master
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/ty.py
Labels: chore

#185 Add test for pipe labels availability
  spacy_llm/tests/pipeline/test_llm.py
Labels: tests, feat/task

#186 Bump version
  setup.cfg
Labels: chore, meta

#187 Synch with `main`
  setup.cfg
  spacy_llm/tests/pipeline/test_llm.py
Labels: chore

#188 Fix cache and nlp.pipe(..., as_tuples=True)
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/pipeline/test_llm.py
Labels: bug

#193 Update readme for `spacy.TextCat.v3`
  README.md
Labels: documentation

#196 Update `langchain` pin
  requirements-dev.txt
Labels: chore, feat/backend
