Repository explosion/spacy-llm, pull requests merged in 2023-08, with the labels that each got.

#237 Bump LangChain to 0.0.249
  requirements-dev.txt
Labels: chore

#167 Add explosion-bot workflow
  .github/workflows/explosionbot.yml
Labels: chore

#239 add old spancat/ner versions to legacy module
  spacy_llm/errors.py
  spacy_llm/tasks/__init__.py
  spacy_llm/tasks/legacy/__init__.py
  spacy_llm/tasks/legacy/ner.py
  spacy_llm/tasks/legacy/span.py
  spacy_llm/tasks/legacy/spancat.py
  spacy_llm/tasks/util/examples.py
  spacy_llm/tests/tasks/legacy/__init__.py
  spacy_llm/tests/tasks/legacy/examples/ner.json
  spacy_llm/tests/tasks/legacy/examples/ner.jsonl
  spacy_llm/tests/tasks/legacy/examples/ner.yml
  spacy_llm/tests/tasks/legacy/examples/ner_inconsistent.yml
  spacy_llm/tests/tasks/legacy/templates/ner.jinja2
  spacy_llm/tests/tasks/legacy/test_ner.py
  spacy_llm/tests/tasks/legacy/test_spancat.py
Labels: feat/task

#245 Modify GH workflows to allow running them from comments
  .github/workflows/external.yml
  .github/workflows/test_gpu.yml
Labels: feature, meta

#247 Add checks action for external tests
  .github/workflows/test_external.yml
Labels: enhancement

#248 Change access token for check runs
  .github/workflows/test_external.yml
Labels: bug, CI

#249 Remove checks action
  .github/workflows/test_external.yml
Labels: bug, CI

#254 CI: add label trigger for GPU tests, remove comment trigger
  .github/workflows/test_external.yml
  .github/workflows/test_gpu.yml
Labels: enhancement, CI

#262 Synch `develop` with `main`
  .github/workflows/test_external.yml
  .github/workflows/test_gpu.yml
  pyproject.toml
  requirements-dev.txt
  spacy_llm/tasks/rel.py
Labels: chore

#243 Register `llm_TASK` factories
  spacy_llm/tasks/__init__.py
  spacy_llm/tests/pipeline/test_llm.py
Labels: feat/task, Test external

#265 remove redundant _examples field
  spacy_llm/tasks/sentiment.py
  spacy_llm/tasks/summarization.py
Labels: feat/task

#267 Remove teams check in GPU and external test workflows
  .github/workflows/test_external.yml
  .github/workflows/test_gpu.yml
Labels: chore, CI

#268 Sync dev with main
  .github/workflows/test_external.yml
  .github/workflows/test_gpu.yml
  spacy_llm/tasks/__init__.py
  spacy_llm/tests/pipeline/test_llm.py
Labels: chore

#270 Add default example if none are provided to COT NER/SpanCat tasks
  pyproject.toml
  spacy_llm/tasks/rel/util.py
  spacy_llm/tasks/templates/ner.v3.jinja
  spacy_llm/tasks/templates/spancat.v3.jinja
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_spancat.py
Labels: enhancement, feat/task

#271 Add usage example for TextCat with Dolly 2
  usage_examples/ner_dolly/examples.yml
  usage_examples/tests/test_usage_examples.py
  usage_examples/textcat_dolly/README.md
  usage_examples/textcat_dolly/__init__.py
  usage_examples/textcat_dolly/examples.jsonl
  usage_examples/textcat_dolly/fewshot.cfg
  usage_examples/textcat_dolly/run_pipeline.py
  usage_examples/textcat_dolly/zeroshot.cfg
Labels: documentation, enhancement

#274 Unit test for comma in entity
  spacy_llm/tests/tasks/test_ner.py
Labels: tests, Test external
