Repository explosion/spacy-llm, pull requests merged in 2023-05, with the labels that each got.

#71 Skip tests if openai key is not available
  spacy_llm/compat.py
  spacy_llm/tests/backends/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: tests

#78 Add Slack monitoring hook
  .github/workflows/external.yml
Labels: feature

#76 strip response so binary textcat works
  spacy_llm/tasks/textcat.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: bug

#79 Bump to v0.1.2 & add push-tags.sh
  push-tags.sh
  setup.cfg
Labels: chore

#88 `external.yaml`: notify Slack only on failure
  .github/workflows/external.yml
Labels: chore

#89 Move `has_openai_key` into tests
  spacy_llm/compat.py
  spacy_llm/tests/backends/test_rest.py
  spacy_llm/tests/compat.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: chore, tests

#90 chore: remove unused zip over prompts in OpenAI backend
  spacy_llm/backends/rest/backend/openai.py
Labels: chore

#93 Use Path.is_dir() instead of os.path
  spacy_llm/cache.py
Labels: chore

#92 fix cache config type
  spacy_llm/cache.py
  spacy_llm/compat.py
  spacy_llm/pipeline/llm.py
Labels: chore

#94 Add link to the external tests in the build badge
  README.md
Labels: documentation, chore

#96 Fix OpenAI requests for chat endpoint
  .github/PULL_REQUEST_TEMPLATE.md
  spacy_llm/backends/rest/backend/openai.py
  spacy_llm/tests/backends/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
Labels: bug, backend

#83 Inspect type vars in `Iterable` arguments for type check
  spacy_llm/pipeline/llm.py
Labels: chore

#91 Set `LLMWrapper._task` on init instead of separate `_template`/`_parse`
  spacy_llm/pipeline/llm.py
Labels: chore, refactoring

#100 Use `test.yml` status for build badge & deactivate notifications for failed `external.yml` runs
  .github/workflows/external.yml
  README.md
Labels: chore

#98 Use NoOp REST backend in tests where reasonable
  spacy_llm/tests/backends/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
Labels: chore, tests

#103 Add workflow, fixes for GPU test pipeline
  .github/workflows/test_gpu.yml
  requirements-dev.txt
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
Labels: feature, tests

#104 fix: caching and cache interaction
  spacy_llm/cache.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/pipeline/test_llm.py
Labels: bug, tests

#108 Fix BuildKite secret name
  .github/workflows/test_gpu.yml
Labels: bug

#99 improve textcat task by better constraining its output and giving a more detailed task intro
  spacy_llm/tasks/textcat.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: enhancement, task

#109 Modify checklist for tests to run
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#111 Lower langchain pin
  requirements-dev.txt
Labels: bug

#112 Remove `langchain` pin, ignore `sqlalchemy` warning
  pyproject.toml
  requirements-dev.txt
Labels: enhancement

#116 ci: temporarily disable fail-fast
  .github/workflows/test.yml
Labels: bug

#115 Add MiniChain and LangChain examples
  .github/workflows/test.yml
  README.md
  spacy_llm/tests/backends/test_rest.py
  usage_examples/README.md
  usage_examples/multitask_openai/README.md
  usage_examples/multitask_openai/__init__.py
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/run_pipeline.py
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/ner_dolly/README.md
  usage_examples/ner_dolly/__init__.py
  usage_examples/ner_dolly/examples.yml
  usage_examples/ner_dolly/fewshot.cfg
  usage_examples/ner_dolly/run_pipeline.py
  usage_examples/ner_dolly/zeroshot.cfg
  usage_examples/ner_langchain_openai/README.md
  usage_examples/ner_langchain_openai/__init__.py
  usage_examples/ner_langchain_openai/ner.cfg
  usage_examples/ner_langchain_openai/run_pipeline.py
  usage_examples/ner_minichain_openai/README.md
  usage_examples/ner_minichain_openai/__init__.py
  usage_examples/ner_minichain_openai/ner.cfg
  usage_examples/ner_minichain_openai/run_pipeline.py
  usage_examples/tests/test_usage_examples.py
  usage_examples/textcat_openai/README.md
  usage_examples/textcat_openai/__init__.py
  usage_examples/textcat_openai/examples.jsonl
  usage_examples/textcat_openai/fewshot.cfg
  usage_examples/textcat_openai/run_pipeline.py
  usage_examples/textcat_openai/zeroshot.cfg
Labels: tests

#118 revert: add fail-fast back
  .github/workflows/test.yml
Labels: chore

#119 build: extra require for `langchain`, `minichain`, `transformers`
  README.md
  setup.cfg
Labels: feature

#120 Make cache object configurable
  README.md
  spacy_llm/cache.py
  spacy_llm/pipeline/llm.py
  spacy_llm/registry/util.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/test_cache.py
  spacy_llm/ty.py
  usage_examples/tests/test_usage_examples.py
Labels: documentation, chore

#123 Stop external tests after first failure
  .github/workflows/external.yml
Labels: tests

#114 feat: REL task
  .github/workflows/external.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  spacy_llm/tasks/__init__.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/templates/rel.jinja
  spacy_llm/tests/tasks/examples/rel_examples.jsonl
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/util.py
  usage_examples/rel_openai/README.md
  usage_examples/rel_openai/__init__.py
  usage_examples/rel_openai/examples.jsonl
  usage_examples/rel_openai/fewshot.cfg
  usage_examples/rel_openai/run_pipeline.py
  usage_examples/rel_openai/zeroshot.cfg
  usage_examples/tests/test_usage_examples.py
Labels: task

#84 update NER prompt and add label definitions to better instruct the LLM
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/templates/ner.v2.jinja
  spacy_llm/tasks/templates/spancat.v2.jinja
  spacy_llm/tasks/util/span.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/test_combinations.py
  usage_examples/ner_dolly/fewshot.cfg
  usage_examples/ner_dolly/zeroshot.cfg
  usage_examples/tests/test_readme_examples.py
Labels: enhancement, feat/task

#81 Make a separate factory for parsing the input to the LLM task
  README.md
  pyproject.toml
  spacy_llm/registry/reader.py
  spacy_llm/tasks/__init__.py
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/noop.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/templates/textcat.jinja
  spacy_llm/tasks/textcat.py
  spacy_llm/tasks/util/span.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
  spacy_llm/ty.py
  spacy_llm/util.py
  usage_examples/README.md
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/ner_langchain_openai/ner.cfg
  usage_examples/ner_minichain_openai/ner.cfg
  usage_examples/tests/test_readme_examples.py
  usage_examples/textcat_openai/fewshot.cfg
  usage_examples/textcat_openai/zeroshot.cfg
Labels: enhancement, refactoring

#95 Add JinjaReader to read external template files
  MANIFEST.in
  README.md
  spacy_llm/__init__.py
  spacy_llm/registry/__init__.py
  spacy_llm/registry/reader.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tests/tasks/templates/ner_template.jinja2
  spacy_llm/tests/tasks/templates/textcat_template.jinja2
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: feature

#129 fix: use v2 textcat for ext template tests
  spacy_llm/tests/tasks/test_textcat.py
Labels: bug

#128 ci: add caching to validation workflow
  .github/workflows/validate.yml
Labels: enhancement, meta

#125 Use assemble and initialize in README examples
  README.md
  usage_examples/tests/test_readme_examples.py
Labels: documentation, tests

#132 Fix type check issues
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  spacy_llm/backends/integration/langchain.py
  spacy_llm/backends/integration/minichain.py
  spacy_llm/backends/rest/backend/openai.py
  spacy_llm/tests/backends/test_langchain.py
  spacy_llm/tests/backends/test_minichain.py
  spacy_llm/tests/test_combinations.py
  spacy_llm/ty.py
Labels: bug, feat/backend

#138 Fix duplicate spacy.TextCat.v1 section
  README.md
Labels: documentation

#134 Fix and add tests for misc entry points
  setup.cfg
  spacy_llm/tests/test_registry.py
Labels: bug

#144 Small type and typo fixes
  README.md
  spacy_llm/cache.py
  usage_examples/ner_langchain_openai/README.md
  usage_examples/ner_minichain_openai/README.md
Labels: documentation

#145 Bump version to 0.2.0
  setup.cfg
Labels: chore, meta

#146 Drop requirement for `sqlalchemy`
  pyproject.toml
  requirements-dev.txt
  setup.cfg
Labels: bug

#147 add util method to component for processing list of docs
  spacy_llm/cache.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/test_cache.py
Labels: refactoring

#137 Allows labels config to be a list or comma-separated str
  README.md
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/textcat.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
  usage_examples/tests/test_readme_examples.py
Labels: enhancement, feat/task

#148 Rephrase PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#135 feat: scoring
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/textcat.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: feature

#150 Rename 'Regression Tests' to 'Core tests'
  .github/workflows/test.yml
Labels: meta
