Repository explosion/spacy-llm, pull requests merged in 2023-07, with the labels that each got.

#179 Add Falcon HF model
  README.md
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  spacy_llm/models/hf/__init__.py
  spacy_llm/models/hf/falcon.py
  spacy_llm/tests/models/test_falcon.py
  usage_examples/README.md
Labels: feature, feat/model

#197 Explicitly display error codes
  spacy_llm/backends/rest/base.py
Labels: enhancement

#199 Adjust model names to title case
  README.md
  migration_guide.md
  spacy_llm/models/rest/anthropic/registry.py
  spacy_llm/models/rest/cohere/registry.py
  spacy_llm/models/rest/openai/registry.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tests/models/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/tasks/test_lemma.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
  spacy_llm/tests/test_combinations.py
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/rel_openai/fewshot.cfg
  usage_examples/rel_openai/zeroshot.cfg
  usage_examples/tests/test_readme_examples.py
  usage_examples/textcat_openai/fewshot.cfg
  usage_examples/textcat_openai/zeroshot.cfg
Labels: chore, feat/model

#163 feat: create examples on init
  README.md
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/lemma.py
  spacy_llm/tasks/ner.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/span.py
  spacy_llm/tasks/spancat.py
  spacy_llm/tasks/textcat.py
  spacy_llm/tasks/util/__init__.py
  spacy_llm/tasks/util/examples.py
  spacy_llm/tasks/util/serialization.py
  spacy_llm/tests/tasks/test_lemma.py
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: enhancement, feature

#183 Detect label inconsistency in `SpanTask`
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/span.py
  spacy_llm/tests/tasks/examples/ner_inconsistent.yml
  spacy_llm/tests/tasks/test_ner.py
  spacy_llm/tests/tasks/test_rel.py
  spacy_llm/tests/tasks/test_spancat.py
  spacy_llm/tests/tasks/test_textcat.py
Labels: bug, feat/task

#192 Use prompt template to ensure data consistency in cache directory
  README.md
  spacy_llm/cache.py
  spacy_llm/pipeline/llm.py
  spacy_llm/tasks/lemma.py
  spacy_llm/tasks/noop.py
  spacy_llm/tasks/rel.py
  spacy_llm/tasks/span.py
  spacy_llm/tasks/textcat.py
  spacy_llm/tests/models/test_rest.py
  spacy_llm/tests/pipeline/test_llm.py
  spacy_llm/tests/test_cache.py
  spacy_llm/ty.py
Labels: enhancement, feat/cache

#203 Sync `develop` with `master`
  README.md
  spacy_llm/models/rest/base.py
Labels: chore, meta

#205 Fix regex -> re import
  spacy_llm/tests/tasks/test_summarization.py
Labels: bug

#207 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#206 Optional authentation verification at init time
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/base.py
  spacy_llm/models/rest/cohere/model.py
  spacy_llm/models/rest/noop/model.py
  spacy_llm/models/rest/openai/model.py
  spacy_llm/tests/models/test_anthropic.py
  spacy_llm/tests/models/test_cohere.py
Labels: enhancement, feat/model

#209 Fix OpenLLaMA model names
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  spacy_llm/models/hf/openllama.py
  spacy_llm/tests/models/test_openllama.py
Labels: bug, feat/model

#210 fix model name in documentation
  migration_guide.md
Labels: documentation

#211 Bump version to 0.4.1
  setup.cfg
Labels: chore

#213 Synch `develop` with `main`
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  migration_guide.md
  pyproject.toml
  setup.cfg
  spacy_llm/models/hf/openllama.py
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/base.py
  spacy_llm/models/rest/cohere/model.py
  spacy_llm/models/rest/noop/model.py
  spacy_llm/models/rest/openai/model.py
  spacy_llm/tests/conftest.py
  spacy_llm/tests/models/test_anthropic.py
  spacy_llm/tests/models/test_cohere.py
  spacy_llm/tests/models/test_dolly.py
  spacy_llm/tests/models/test_falcon.py
  spacy_llm/tests/models/test_openllama.py
  spacy_llm/tests/models/test_stablelm.py
  spacy_llm/tests/tasks/test_summarization.py
  usage_examples/tests/test_readme_examples.py
  usage_examples/tests/test_usage_examples.py
Labels: chore

#219 Guard REL against indices higher than the number of entities in the doc
  spacy_llm/tasks/rel.py
  spacy_llm/tests/tasks/test_rel.py
Labels: bug, feat/task

#218 Warning instead of error on auth verification failure in REST models
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/cohere/model.py
  spacy_llm/models/rest/openai/model.py
Labels: enhancement, feat/model

#217 Add support for Anthropic Claude-2
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/anthropic/registry.py
Labels: chore, feat/model

#220 Bump version to 0.4.2.
  setup.cfg
Labels: chore

#222 Fix Falcon HF warnings
  spacy_llm/models/hf/falcon.py
Labels: bug, feat/model

#227 Capital sensitive param
  README.md
Labels: documentation

#229 Bump version
  setup.cfg
Labels: chore

#231 Add Claude 2 support
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/anthropic/registry.py
Labels: feat/model

#233 Catch blocking errors from Cohere
  spacy_llm/models/rest/cohere/model.py
Labels: bug

#235 Fix Claude-2 completions endpoint
  spacy_llm/models/rest/anthropic/model.py
  spacy_llm/models/rest/anthropic/registry.py
Labels: bug
