Repository explosion/spacy-llm, pull requests merged in 2024-01, with the labels that each got.

#417 Fix various API- and LangChain-related issues
  spacy_llm/models/langchain/model.py
  spacy_llm/tests/models/test_cohere.py
  spacy_llm/tests/models/test_langchain.py
  spacy_llm/tests/test_combinations.py
  usage_examples/multitask_openai/fewshot.cfg
  usage_examples/multitask_openai/zeroshot.cfg
  usage_examples/ner_langchain_openai/ner.cfg
Labels: bug, third party

#419 Remove download helper
  download_x.py
Labels: chore

#420 Bump version to 0.7.0
  setup.cfg
Labels: chore

#425 Update doc string
  spacy_llm/models/hf/mistral.py
Labels: documentation

#421 Add more links to spaCy docs
  README.md
Labels: documentation

#427 Sync `dev` with `main`
  README.md
  setup.cfg
  spacy_llm/models/hf/mistral.py
Labels: chore

#430 Fix legacy NER test warning in CI
  spacy_llm/tests/tasks/legacy/test_ner.py
  spacy_llm/tests/tasks/test_ner.py
Labels: bug, tests

#431 Sync `develop` with `main`
  spacy_llm/models/rest/azure/model.py
  spacy_llm/models/rest/openai/model.py
  spacy_llm/tests/tasks/legacy/test_ner.py
  spacy_llm/tests/tasks/test_ner.py
Labels: chore

#434 Fix/index error when unhighlighting
  spacy_llm/tasks/entity_linker/task.py
  spacy_llm/tests/tasks/test_entity_linker.py
Labels: bug, feat/task

#433 Adjust LangChain usage in line with `langchain` >= 0.1
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  spacy_llm/compat.py
  spacy_llm/models/langchain/model.py
Labels: Test external, third party

#435 Bump version to v0.7.1
  setup.cfg
Labels: chore, Test external

#437 Merge `main` into `develop`
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  spacy_llm/compat.py
  spacy_llm/models/langchain/model.py
  spacy_llm/tasks/entity_linker/task.py
  spacy_llm/tests/tasks/test_entity_linker.py
Labels: chore
